image: goblinogm/sphinx-builder

cache:
  paths:
  - vendor

test:
  script:
  - pwd
  - pip install -U -r requirements.txt
  - cd docs
  - make html
  except:
    - master

pages:
  script:
  - pwd
  - ls
  - pip install -U -r requirements.txt
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
